#!/bin/bash
if [ -d "infinittuxai" ]; then
    rm -rf infinittuxai
fi

if [ -d "dist" ]; then
    rm -rf dist
fi   

mkdir infinittuxai
mkdir dist

javac -cp .:./lib/jdom.jar -source 1.6 -target 1.6 -d \
./infinittuxai \
./src/ch/idsia/ai/agents/ai/*.java \
./src/ch/idsia/ai/agents/human/*.java \
./src/ch/idsia/ai/agents/*.java \
./src/ch/idsia/ai/ea/*.java \
./src/ch/idsia/ai/*.java \
./src/ch/idsia/ai/tasks/*.java \
./src/ch/idsia/mario/engine/*.java \
./src/ch/idsia/mario/engine/level/*.java \
./src/ch/idsia/mario/engine/mapedit/*.java \
./src/ch/idsia/mario/engine/sprites/*.java \
./src/ch/idsia/mario/environments/*.java \
./src/ch/idsia/mario/simulation/*.java \
./src/ch/idsia/scenarios/*.java \
./src/ch/idsia/scenarios/test/*.java \
./src/ch/idsia/tools/*.java \
./src/ch/idsia/tools/tcp/*.java \
./src/ch/idsia/utils/*.java \
./src/competition/cig/robinbaumgarten/astar/*.java \
./src/competition/cig/robinbaumgarten/astar/level/*.java \
./src/competition/cig/robinbaumgarten/astar/sprites/*.java \
./src/competition/cig/robinbaumgarten/*.java \
./src/competition/cig/sergeykarakovskiy/*.java \
./src/wox/serial/*.java \


mkdir -p ./infinittuxai/ch/idsia/mario/engine/resources
cp -R ./src/ch/idsia/mario/engine/resources/* ./infinittuxai/ch/idsia/mario/engine/resources

jar cfm infinittuxai.jar manifest.txt -C ./infinittuxai .
mv infinittuxai.jar ./dist
rm -rf infinittuxai

echo "#!/bin/bash" > ./dist/infinittuxai
echo 'MAINCLASS="ch.idsia.scenarios.Play"' >> ./dist/infinittuxai
echo 'OPTION=$1"s"' >> ./dist/infinittuxai
echo 'if [ "$OPTION" == "fs" ]; then' >> ./dist/infinittuxai
echo     'MAINCLASS="ch.idsia.scenarios.Play"' >> ./dist/infinittuxai
echo 'fi' >> ./dist/infinittuxai
echo 'java -cp .:infinittuxai.jar $MAINCLASS' >> ./dist/infinittuxai
chmod +x ./dist/infinittuxai
chmod +x ./dist/infinittuxai.jar





